### ISSUE TITLE
action did not test code

### ISSUE THREAD

**Issue by baerwang** [dubbogo/arana#19]
https://github.com/dubbogo/arana/blob/15aa18f61ae8cadf874d2ead860bd88bb5608d66/test/integration_test.go#L113

action mysql root account password is root, test is 123456, did not fail

**Comment by luky116** [comment]
你这样是直接连接了MySQL，没有走arana代理，所以也能连接成功
![image](https://user-images.githubusercontent.com/38887641/147129176-818912a9-d576-4c11-83cd-ac2b5992c1aa.png)

**Comment by dk-lockdown** [comment]
当前 action 只是把 mysql 跑起来了，还没跑集成测试。
