### ISSUE TITLE
表中有值，也给客户端返回结果了，但是客户端没解析出来

### ISSUE THREAD

**Issue by Penglq** [dubbogo/arana#2]
var v = &struct {
		EmpNo     int       `gorm:"emp_no"`
		BirthDate time.Time `gorm:"birth_date"`
		FirstName string    `gorm:"first_name"`
		LastName  string    `gorm:"last_name"`
		Gender    string    `gorm:"gender"`
		HireDate  time.Time `gorm:"hire_date"`
	}{}

	db, _ := sql.Open("mysql", "dksl:123456@tcp(127.0.0.1:13306)/employees?timeout=1s&readTimeout=1s&writeTimeout=1s&parseTime=true&loc=Local&charset=utf8mb4,utf8") //连接数据库
	defer db.Close()

	row := db.QueryRow(`SELECT emp_no FROM employees`)
	if err := row.Scan(&v.EmpNo); err != nil {
		panic(err)
	}
	fmt.Println(v.EmpNo)
运行结果：
panic: sql: no rows in result set

![image](https://user-images.githubusercontent.com/14035922/145762112-8a866453-fb79-4302-9dff-fa40f43099c9.png)

**What happened**:
表中有值，也给客户端返回结果了，但是客户端没解析出来

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by dk-lockdown** [comment]
报啥错了？

**Comment by dk-lockdown** [comment]
db 啥版本啊

**Comment by Penglq** [comment]
> db 啥版本啊

5.7.34
