### ISSUE TITLE
[bug] ComQuery return only one row, when there is more data rows, bug occur.

### ISSUE THREAD

**Issue by dk-lockdown** [dubbogo/arana#31]
suggest define a configuration item, configure the maxrows.

**What happened**:
<img width="574" alt="A584964E-6121-48D8-9085-66B5EF7F454A" src="https://user-images.githubusercontent.com/33612882/147722523-725fd562-8f58-41ff-9ebc-a43cfa9d0020.png">
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
<img width="768" alt="DD4225B4-FBE8-46C2-8F73-A09C849A45C7" src="https://user-images.githubusercontent.com/33612882/147722563-8ca5cd32-ec4e-46af-a4eb-d834a3d82219.png">

**Anything else we need to know?**:

**Comment by luky116** [comment]
let me see
