### ISSUE TITLE
Cannot connect with mycli

### ISSUE THREAD

**Issue by jjeffcaii** [dubbogo/arana#42]
Cannot connect the arana server over [mycli](https://www.mycli.net/)

The `mycli` is a very popular command-line tool, we should support it.

**What happened**:
1. start server
2. connect with `mycli -h127.0.0.1 -udksl employees -p123456 -P13306`

**What you expected to happen**: Should connect successfully

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by jjeffcaii** [comment]
my local config problem

**Comment by Penglq** [comment]
I can connect with mycli -h127.0.0.1 -udksl employees -p123456 -P13306
![image](https://user-images.githubusercontent.com/14035922/149660569-baf07d26-e814-4756-91de-23bf00e20e61.png)

Although, when it is connected, arana panic.

**Comment by jjeffcaii** [comment]
It seems to work normally in the latest version, closed.
