### ISSUE TITLE
跑集成测试报错了

### ISSUE THREAD

**Issue by luky116** [dubbogo/arana#58]
**What happened**:

当执行集成测试查询时，aranan会报错：
 mysql_server caught panic:
trying to call recycleReadPacket while currentEphemeralPolicy is 0

![image](https://user-images.githubusercontent.com/38887641/153698985-5cdafbe5-3580-4505-b19e-d494fd4e9572.png)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
启动main函数，然后执行 test 包下面的 integration_test.go 文件的 TestSelect方法，即可复现问题

**Anything else we need to know?**:

**Comment by dongzl** [comment]
应该和 #34  是同一个问题
